accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    
    # 주소창엔 언더바를 사용하지 않아서 '-'로 사용
    # READ 부분에서 username으로 bookmark-list 를 인식할 수 있는 문제가 있어(str 이라서) 순서를 위로 올림
    path('bookmark-list/', views.bookmark_list, name='bookmark_list'),

    path('new-speed/', views.new_speed, name='new_speed'),
    
    # CREATE
    path("signup/", views.signup, name='signup'),
    # UPDATE
    path("edit/", views.edit, name='edit'),
    # CREATE
    path("login/", views.login, name='login'),
    # DELETE
    path("logout/", views.logout, name='logout'),
    # READ
    path("<str:username>/", views.profile, name='profile'),

    # CREATE
    path('<int:id>/following/', views.following, name='following'),


]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField
from posts.models import Post
from django.conf import settings
# Create your models here.

class User(AbstractUser):
    following = models.ManyToManyField('self', symmetrical=False, related_name='follower')
    # follower = 라는 컬럼이 자동으로 생김
    # profile_image = models.ImageField(upload_to='profiles')

    profile_image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to = 'profiles',
    )
    bookmarks = models.ManyToManyField(
        Post,
        through='Bookmark',
        related_name='bookmark_users',
    )

class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django_resized import ResizedImageField

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # image = models.ImageField(upload_to='pic/%m/%d')
    image = ResizedImageField(
        size = [500,500],
        crop = ['middle', 'center'],
        upload_to = 'pic/%m/%d'
    )

    # M 대 N 연결
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    # post.like_users.all()
    # user.like_posts.all()


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'profile_image')


class CustomAuthenticationForm(AuthenticationForm):
    pass


class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'profile_image', 'first_name', 'last_name')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomAuthenticationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from posts.models import Post
# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }    
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


def profile(request, username):
    User = get_user_model()
    # user_info = User.objects.get(username=username)
    user_info = get_object_or_404(User, username=username)

    context = {
        'user_info': user_info,
    }

    return render(request, 'accounts/profile.html', context)

@login_required
def following(request, id):
    User = get_user_model()
    
    me = request.user
    you = User.objects.get(id=id)

    if me != you:
        # if me in you.follower.all():
        if you in me.following.all():
            me.following.remove(you)
        else:
            me.following.add(you)

    return redirect('accounts:profile', you.username)

@login_required
def edit(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user.username)

    else:
        form = CustomUserChangeForm(instance=request.user)

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)

@login_required
def bookmark_list(request):
    # order_by : 정렬
    # 작성시간 기준 내림차순정렬 ('-' : 최신 순 정렬)
    bookmarks = request.user.bookmark_set.all().order_by('-created_at')

    context = {
        'bookmarks': bookmarks,
    }

    return render(request, 'accounts/bookmark_list.html', context)

@login_required
def new_speed(request):
    user = request.user
    # filter : 조건에 맞는 것만 필터
    # Lookups (__in) : 
    posts = Post.objects.filter(user__in=user.following.all())
    
    context = {
        'posts': posts,
    }

    return render(request, 'posts/index.html', context)

accounts/templates/accounts/bookmark_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="m-2">
        <div class="row">
            <img src="{{user.profile_image.url}}" alt="" class="col-3 rounded-circle">    
            <div class="col-9">
                <h1 class="text-center">{{user.username}}</h1>
            </div>
        </div>
    </div>

    <div>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for bookmark in bookmarks %}
                <!-- with : 변수 할당 -->
                {% with post=bookmark.post %}
                <div class="col">
                    {% include 'posts/_card.html' %}
                </div>
                {% endwith %}
            {% endfor%}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load socialaccount %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>

    <a href="{% provider_login_url 'github' next='/posts/'' %}" class="btn btn-primary">github</a>
    <a href="{% provider_login_url 'google' next='/posts/'' %}" class="btn btn-primary">google</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="m-2">
        <div class="row">
            {% if user_info.profile %}
                <img src="{{user_info.profile_image.url}}" alt="" class="col-3 rounded-circle">    
            {% else %}
                <img src="https://picsum.photos/200" alt="" class="col-3 rounded-circle">
            {% endif %}
            <div class="col-9">
                <h1 class="text-center">{{user_info.username}}</h1>
                <p>follower : {{user_info.follower.all|length}}명</p>
                <p>following : {{user_info.following.all|length}}명</p>

                {% if user != user_info %}
                    {% if user in user_info.follower.all %}
                        <a href="{% url 'accounts:following' user_info.id %}" class="btn btn-danger">unfollow</a>
                    {% else %}
                        <a href="{% url 'accounts:following' user_info.id %}" class="btn btn-primary">following</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'accounts:edit' %}" class="btn btn-primary">edit</a>    
                    <a href="{% url 'accounts:bookmark_list' %}" class="btn btn-primary">bookmark list</a>
                {% endif %}
            </div>
        </div>

    </div>

    <div>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for post in user_info.post_set.all %}
                <div class="col">
                    {% include 'posts/_card.html' %}
                </div>
            {% endfor%}
        </div>
    </div>
{% endblock %}