accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    
    # 주소창엔 언더바를 사용하지 않아서 '-'로 사용
    # READ 부분에서 username으로 bookmark-list 를 인식할 수 있는 문제가 있어(str 이라서) 순서를 위로 올림
    path('bookmark-list/', views.bookmark_list, name='bookmark_list'),

    path('new-speed/', views.new_speed, name='new_speed'),
    
    # CREATE
    path("signup/", views.signup, name='signup'),
    # UPDATE
    path("edit/", views.edit, name='edit'),
    # CREATE
    path("login/", views.login, name='login'),
    # DELETE
    path("logout/", views.logout, name='logout'),
    # READ
    path("<str:username>/", views.profile, name='profile'),

    # CREATE
    path('<int:id>/following/', views.following, name='following'),


]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # READ
    path('', views.index, name='index'),
    # CREATE
    path('create/', views.create, name='create'),
    # DELETE
    path('<int:id>/delete/', views.delete, name='delete'),

    # CREATE
    path('<int:id>/comments/create/', views.comments_create, name='comments_create'),
    
    # CREATE
    path('<int:id>/likes/', views.likes, name='likes'),
    path('<int:id>/likes-async/', views.likes_async, name='likes_async'),

    path('<int:id>/bookmarks', views.bookmarks, name='bookmarks'),

]

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <i class="fa-brands fa-instagram fa-2xl"></i>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'posts:create' %}">
                  <i class="fa-solid fa-plus"></i>
                </a>
                <a class="nav-link" href="{% url 'accounts:profile' user.username %}">
                  {{user}}
                </a>
                <a class="nav-link" href="{% url 'accounts:logout' %}">logout
                  <i class = 'fa-solid fa-right-from-bracket'></i>
                </a>
                <a href="{% url 'accounts:new_speed' %}" class="nav-link">
                  new speed
                </a>
            {% else %}
                <a class="nav-link" href="{% url 'accounts:signup' %}">signup</a>
                <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
            {% endif %}
        </div>
      </div>
    </div>
</nav>

templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!--  css 버전 차이로 부트스트랩 css 가져옴 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    {% include '_nav.html' %}
    <div class="container">
        {% block content %}
        {% endblock %} 
    </div>
    
    {% bootstrap_javascript %}
    <script src="https://kit.fontawesome.com/18ec0fbb8a.js" crossorigin="anonymous"></script>
</body>
</html>