accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    
    # 주소창엔 언더바를 사용하지 않아서 '-'로 사용
    # READ 부분에서 username으로 bookmark-list 를 인식할 수 있는 문제가 있어(str 이라서) 순서를 위로 올림
    path('bookmark-list/', views.bookmark_list, name='bookmark_list'),

    path('new-speed/', views.new_speed, name='new_speed'),
    
    # CREATE
    path("signup/", views.signup, name='signup'),
    # UPDATE
    path("edit/", views.edit, name='edit'),
    # CREATE
    path("login/", views.login, name='login'),
    # DELETE
    path("logout/", views.logout, name='logout'),
    # READ
    path("<str:username>/", views.profile, name='profile'),

    # CREATE
    path('<int:id>/following/', views.following, name='following'),


]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # READ
    path('', views.index, name='index'),
    # CREATE
    path('create/', views.create, name='create'),
    # DELETE
    path('<int:id>/delete/', views.delete, name='delete'),

    # CREATE
    path('<int:id>/comments/create/', views.comments_create, name='comments_create'),
    
    # CREATE
    path('<int:id>/likes/', views.likes, name='likes'),
    path('<int:id>/likes-async/', views.likes_async, name='likes_async'),

    path('<int:id>/bookmarks', views.bookmarks, name='bookmarks'),

]

posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django_resized import ResizedImageField

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # image = models.ImageField(upload_to='pic/%m/%d')
    image = ResizedImageField(
        size = [500,500],
        crop = ['middle', 'center'],
        upload_to = 'pic/%m/%d'
    )

    # M 대 N 연결
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    # post.like_users.all()
    # user.like_posts.all()


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image',)


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':'1'}))
    class Meta:
        model = Comment
        fields = ('content', )        

posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, CommentForm
from .models import Post
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.
def index(request):
    posts = Post.objects.all()
    comment_form = CommentForm()

    context = {
        'posts':posts,
        'comment_form': comment_form,
    }

    return render(request, 'posts/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form': form,
    }
    return render(request, 'posts/form.html', context)

@login_required
def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('posts:index')

@login_required
def comments_create(request, id):
    post = Post.objects.get(id=id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('posts:index')
        
@login_required
def likes(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    # 둘중 아무거나 사용해도 됨      
    # user.like_posts.add(post)  
    # post.like_users.add(user)

    # 이미 좋아요 누른 경우
    # 아래의 두 코드 다 같은 기능
    # if post.like_users.filter(id=user.id).exists():
    if user in post.like_users.all():
        user.like_posts.remove(post)
    # 아직 좋아요 안누른 경우
    else:
        user.like_posts.add(post)

    return redirect('posts:index')

@login_required
def bookmarks(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    # 둘 다 같은 기능
    # if user in post.bookmark_users.all():
    if post in user.bookmarks.all():    
        user.bookmarks.remove(post)
    else:
        user.bookmarks.add(post)

    return redirect('posts:index')

def likes_async(request, id):
    # context = {
    #     'msg': 'hello',
    #     'id': id,
    # }

    user = request.user
    post = Post.objects.get(id=id)

    if user in post.like_users.all():
        user.like_posts.remove(post)
        status = False
    else:
        user.like_posts.add(post)
        status = True

    context = {
        'status': status,
        'count': len(post.like_users.all())
    }

    return JsonResponse(context)

posts/templates/posts/_card.html
{% load bootstrap5 %}
<div class="card mb-3" style="width: 18rem;">
    <div class="card-header">
        <a href="{% url 'posts:bookmarks' post.id %}" class="text-reset text-decoration-none">
            {% if user in post.bookmark_users.all %}
                <i class="fa-solid fa-bookmark"></i>{{bookmark.created_at|timesince}} 
            {% else %}
                <i class="fa-regular fa-bookmark"></i>
            {% endif %}
        </a>
    </div>
    <img src="{{post.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
        <p>
            <!-- <a href="{% url 'posts:likes' post.id %}" class="text-reset text-decoration-none"> -->
                {% if user in post.like_users.all %}
                    <i class="fa-solid fa-heart" style="color: red" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i>
                {% else %}
                    <i class="fa-regular fa-heart" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i>
                {% endif %}
                 명이 좋아합니다.
            <!-- </a> -->
        </p>
        <p class="card-text">{{post.content}}</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->

        {% if post.user == user %}
        <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger btn-sm">delete</a>
        {% endif %}

    </div>
    <div class="card-footer text-body-secondary">
        {{post.created_at|timesince}}

    </div>
    {% if request.resolver_match.url_name != 'profile' %}
    <ul class="list-group list-group-flush">
        {% for comment in post.comment_set.all %}
            <li class="list-group-item"><a href="{% url 'accounts:profile' comment.user.username %}">{{comment.user}}</a> : {{comment.content}}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if comment_form %}
    <div class="card-body">
        <form action="{% url 'posts:comments_create' post.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit" class="btn btn-sm btn-primary">
        </form>
    </div>
    {% endif %}
</div>

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class ='btn btn-primary' type="submit">
    </form>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}


{% block content %}
    <h1>index</h1>
    {% for post in posts %}
        {% include 'posts/_card.html' %}
    {% endfor %}

    <script>
        // console.log('hello')
        const likeButtons = document.querySelectorAll('i.fa-heart')
        // console.log(likeButtons)

        likeButtons.forEach((btn)=>{
            // console.log(btn)
            btn.addEventListener('click', (event)=>{
                // console.log(event.target)
                const postId = event.target.dataset.postId
                // console.log(postId)

                // 장고로 user가 postId 게시물을 좋아합니다라는 요청을 보낸다
                likeRequest(btn, postId)

            })
        })

        async function likeRequest(btn, postId) {
            const likeURL = `/posts/${postId}/likes-async/`
            // console.log(likeURL)
            const response = await fetch(likeURL)
            const result = await response.json()
            console.log(result)

            if (result.status) {
                btn.style.color = 'red'
                btn.classList.remove('fa-regular')
                btn.classList.add('fa-solid')
                btn.innerHTML = result.count
            } else {
                btn.style.color = 'black'
                btn.classList.remove('fa-solid')
                btn.classList.add('fa-regular')
                btn.innerHTML = result.count
            }
        }
    </script>
{% endblock %}